# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2
# Use a package of configuration called an orb.
jobs:
    build:
      docker:
      - image: gcc:8.2
      
      steps:
      - checkout
      - run: gcc `pkg-config --cflags gtk+-3.0` -o cryptech  main.c `pkg-config --libs gtk+-3.0` -rdynamic
      - run: ./cryptech